name: Latest Medium blog posts

on:
  schedule:
    - cron: "0 0 * * *" # every day at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@fardee.useng"
          max_post_count: 5
          template: "- 📌 [$title]($url)$newline"
          commit_message: "docs: update latest Medium blog posts"
